import Head from "next/head";
import Image from "next/image";
import InvoiceList from "../components/InvoiceList.tsx";
// import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>Invoice - Next App</title>
        <meta
          name="description"
          content="Invoice - Generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <InvoiceList />
      </main>
    </>
  );
}
