import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import Header from "../components/Header.tsx";
import InvoiceList from "../components/InvoiceList.tsx";
// import styles from "../styles/Home.module.css";

export default function Home() {
  const [darkTheme, setDarkTheme] = useState(true);

  return (
    <>
      <Head>
        <title>Invoice - Next App</title>
        <meta
          name="description"
          content="Invoice - Generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <main className={styles.main}> */}
      <main>
        <Header darkTheme={darkTheme} setDarkTheme={setDarkTheme} />
        <InvoiceList />
      </main>
    </>
  );
}
